version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./Database/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./BackEnd/java/employee-with-graphql
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./Database/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./FrontEnd/Nextjs/ts_employ_graphql
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend # ❗호스트 포트 매핑 불필요, Nginx가 대신 받음
    networks:
      - app-network

  nginx:
    build:
      context: ./Infra/nginx
      dockerfile: Dockerfile-java
    container_name: nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"      # 외부에서 접속은 항상 Nginx를 통해
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge