spring.application.name=employee-with-graphql
server.port=8080
spring.main.allow-bean-definition-overriding=true
# ================================
# PostgreSQL
# ================================
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:mydb}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
# ================================
# JPA
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================================
# GraphQL
# ================================
spring.graphql.path=/graphql
spring.graphql.schema.locations=classpath:/graphql/
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# ================================
# CORS (Next.js) - Handled by WebConfig.java
#spring.graphql.cors.allowed-origins=http://localhost:3000
#spring.graphql.cors.allowed-methods=GET,POST
#spring.graphql.cors.allowed-headers=*